### ISSUE TITLE
Shift/Queue + Click only works for p1

### ISSUE THREAD

**Issue by Flaxative** [Flaxative/wretch#4]
If you try to issue a queued order when the active player is p2 or p3, it instead issues a queued order to p1. :\

(If you try to issue multiple, the last one you issue replaces the queued order on p1 ... which apparently is  NOT storing a list of these orders.)

**Comment by DukeTresnor** [comment]
Is the function for making the queued orders part of the code for p1, or is the call for them within p1 a child of the general queued order function?

I'm sorry if this makes no sense. I also don't entirely get it.

**Comment by Flaxative** [comment]
I checked for that. The function is a method on the state class. And there's no way anyone could 'get it' without looking at the code, which hopefully you and I can do together sometime soon ^_^

**Comment by Flaxative** [comment]
Hahaha finally fixed it. Had to look everywhere, because every time I logged something to make sure the code was looking at the right player, it looked correct. (P2 was receiving the command, P2 was queueing successfully, P2 was executing the queued commands, P2's state was changing correctly...)

Problem was I was setting the destination on P1's agent variable. All good now. =)
